version: 0.1.{build}

image: Visual Studio 2015

environment:
  matrix:
    # Python 3.5.3 - 64-bit
    - PYTHON: "C:\\Python35-x64"

#---------------------------------#
#        build                    #
#---------------------------------#

build: off

configuration: Release

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;C:\MinGW\bin
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
  - python --version
  - make install

after_test:
  - make package
  - '7z a DEXBot-cli-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-cli.exe'
  - '7z a DEXBot-gui-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-gui.exe'

# @TODO: Run tests..
test_script:
  - "echo tests..."

artifacts:
  - path: DEXBot-cli-win64.zip
    name: DEXBot-cli-win64.zip

  - path: DEXBot-gui-win64.zip
    name: DEXBot-gui-win64.zip

#---------------------------------#
#        deployment               #
#---------------------------------#

shallow_clone: false

clone_depth: 1

deploy:
  - provider: GitHub
    artifacts:
      - "DEXBot-cli-win64.zip"
      - "DEXBot-gui-win64.zip"
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: gWZ2Z2oiSx2PBs30bkrYnLzUHhE5Bh8lzH2oprBVGkI+7SES9d7iP8U7dJ/yM9aV
    on:
      appveyor_repo_tag: true     # deploy on tag push only
